export const staticAchievements = [
    {
        id: 1,
        title: "How to Become a Flutter Developer: From Zero to Hero",
        description: "A comprehensive course on Flutter development.",
        category: "Academic",
        is_show: true,
        image: "/images/achievements/certificates/Sertifikat 035_SER_B2G-MKP_XII_2022 - FERI ADRIAN.jpg",
        name: "Flutter",
        issuing_organization: "Alterra Academy",
        url_credential: "No online verification available",
        issue_date: "2022-12-28",
    },
    {
        id: 2,
        title: "Apps Developer With Flutter",
        description: "Completed an internship focused on Flutter app development.",
        category: "Academic",
        is_show: true,
        image: "/images/achievements/certificates/Achievements-intern.jpg",
        name: "Internship",
        issuing_organization: "PT. Menara Indonesia",
        url_credential: "No online verification available",
        issue_date: "2023-07-28",
    },
    {
        id: 3,
        title: "Creating 3D Animation Layout",
        description: "Completed an internship focused on Flutter app development.",
        category: "Academic",
        is_show: true,
        image: "/images/achievements/certificates/Achievements-3dlayout.jpg",
        name: "3D Animation Layout",
        issuing_organization: "Balai Diklat Industri Bali",
        url_credential: "No online verification available",
        issue_date: "2022-04-28",
    },
    // dan seterusnya
];
