export const staticAchievements = [
    {
        id: 1,
        title: "How to Become a Flutter Developer: From Zero to Hero",
        description: "A comprehensive course on Flutter development.",
        category: "Academic",
        is_show: true,
        image: "/images/achievements/certificates/Sertifikat 035_SER_B2G-MKP_XII_2022 - FERI ADRIAN.jpg",
        name: "How to Become a Flutter Developer: From Zero to Hero",
        issuing_organization: "Alterra Academy",
        url_credential: process.env.DOMAIN || 'https://feriadrian.site.vercel.app',
        issue_date: "2022-12-28",
    },
    {
        id: 2,
        title: "Apps Developer With Flutter",
        description: "Completed an internship focused on Flutter app development.",
        category: "Academic",
        is_show: true,
        image: "/images/achievements/certificates/Achievements-intern.jpg",
        name: "Apps Developer With Flutter",
        issuing_organization: "PT. Menara Indonesia",
        url_credential: process.env.DOMAIN || 'https://feriadrian.site.vercel.app',
        issue_date: "2023-07-28",
    },
    {
        id: 3,
        title: "Creating 3D Animation Layout",
        description: "Completed an internship focused on Flutter app development.",
        category: "Academic",
        is_show: true,
        image: "/images/achievements/certificates/Achievements-3dlayout.jpg",
        name: "Creating 3D Animation Layout",
        issuing_organization: "Balai Diklat Industri Bali",
        url_credential: process.env.DOMAIN || 'https://feriadrian.site.vercel.app',
        issue_date: "2022-04-28",
    },
    {
        id: 4,
        title: "Excel Untuk Bantu Kariermu",
        description: "Completed an internship focused on Flutter app development.",
        category: "Academic",
        is_show: true,
        image: "/images/achievements/certificates/Sertifikat Excel untuk Bantu Kariermu.jpg",
        name: "Excel Untuk Bantu Kariermu",
        issuing_organization: "Jobstreet Career Hub",
        url_credential: process.env.DOMAIN || 'https://feriadrian.site.vercel.app',
        issue_date: "2025-06-12",
    },
    {
        id: 5,
        title: "Pelatihan Excel untuk Admin ",
        description: "Completed an internship focused on Flutter app development.",
        category: "Academic",
        is_show: true,
        image: "/images/achievements/certificates/Sertifikat Excel untuk Bantu Kariermu.jpg",
        name: "Pelatihan Excel untuk Admin ",
        issuing_organization: "Jobstreet Career Hub",
        url_credential: process.env.DOMAIN || 'https://feriadrian.site.vercel.app',
        issue_date: "2025-06-12",
    },
    // dan seterusnya
];
